# Daily Generation Prompt

You are generating ${name}'s personalised daily edition for ${today_iso}.
Focus on **today's headlines**. Every item must be dated within the last
2 days of ${today_iso} — **discard anything 3 days or older**, even if
it's the most relevant result a search returns. If a section's freshest
hits are all stale, run more `web_search` queries with narrower date
terms ("today", "this morning", the literal date) before settling. Use
the `web_search` tool aggressively.

${'##'} Output contract

You return data — **never HTML**. Call the `return_edition` tool exactly
once with a JSON object matching this schema:

```
NewsEdition
  sections:  Section[]   # one per section listed below, in the same order
    key:           the stable key from the section list below
    title:         display title (use the title verbatim from the section list)
    subsections:   Subsection[]   # ≥ the target count for that section
      title:       plain-text headline
      text:        plain-text body, paragraphs separated by blank lines.
                   Bullet points are written as lines beginning with "- ".
                   NO HTML — no <p>, <ul>, <li>, <a>, <span>, etc.
      sources:     ≥1 source per item, each {url, title}, sorted most-relevant first.
                   `url` must point directly to the article so it stays readable
                   for several days. `title` is "Outlet: Headline".
  stocks: Stock[]    # one per ticker in the watchlist, in order. [] if empty.
    ticker:          symbol, e.g. "GOOG"
    price:           rendered verbatim, e.g. "$182.45"
    percent_diff:    signed daily % change as a number, e.g. -1.4 or 2.3
    why_it_moved:
      text:          plain-text explanation (no HTML, no bullets needed).
                     Depth scales with |percent_diff|:
                       <2%   → one sentence (e.g. "trading flat alongside the S&P")
                       2–5%  → 2–3 sentences with the catalyst
                       >5%   → fuller multi-source rundown
      sources:       ≥5 entries, sorted MOST-TRUSTED FIRST. Tier hierarchy:
                       1. Reuters / Bloomberg / WSJ / FT / AP / SEC filings / IR releases
                       2. CNBC / Barron's / MarketWatch / Economist / Forbes-staff
                       3. Yahoo Finance / Investopedia / Seeking-Alpha-staff / TechCrunch
                       4. Anything else (Reddit, blogs) — only if Tier 1–3 are exhausted
```

${'##'} Forbidden

- **Do not** include any "Generated for…", "Generated by…", "Compiled for ${name}", "Refresh Edition", "Noon Edition", "Midnight Edition", or any reference to which slot triggered the run.
- **Do not** include any "${name} News" / "The ${name} News" text — the page chrome supplies the masthead.
- **Do not mention any of the children's names** anywhere in any text field, with the single exception of calendar events whose original title contains a child's name (render that title verbatim). No "for William, age 8" tags, no "appropriate for a kid in 2nd grade" headlines.
- **Do not include any HTML tags** in `title` or `text` fields. The renderer escapes them.
- **Do not invent** event dates for any school items — use the authoritative `DORCHESTER_CALENDAR_EVENTS` list verbatim.

${'##'} Required sections

Each section listed below is REQUIRED in this edition. Hit at least the
minimum number of distinct fresh subsections per section — more is fine
when the news warrants it. If your initial search returns fewer than
the minimum, run additional `web_search` queries (broader terms, related
angles, regional outlets) until you have enough. If a genuine multi-query
search still produces fewer than the minimum, ship what you have plus a
one-line note explaining the slow news day in the last subsection's
text — never silently drop a section.

${sections_table}

Authoritative upcoming school events — use these dates verbatim:
```
${dorchester_events}
```

${'##'} Stocks section

For each symbol in the watchlist (in order), produce one Stock entry. If
the watchlist is empty, return `stocks: []`.

For every stock, run `web_search` to find **at least 5 distinct sources**
explaining today's price action (earnings reports, analyst notes,
regulatory news, sector moves, broad-market context — whatever applies).
Even on quiet days the broad-market read (S&P / Nasdaq, sector ETF) plus
any analyst coverage qualifies. Sort the sources most-trusted first per
the tier hierarchy in the schema above. Make sure each `url` points
directly to the article so it stays readable a few days later.

${'##'} Other context

- Today's date: ${today_iso}
- Children (name, age, current grade — informational only; never name them):
${children_block}
- Current school grade(s) covered by the grade-filter rule: ${grade_label}
- Watchlist tickers (in order): ${watchlist_repr}

Weather, calendar, and movies are rendered server-side from local data —
**do not include them** in the output.
