"""Build the daily-edition prompt for Claude.

This module replaces the old static ``news.pr`` file. The section table is
no longer hardcoded — it's pulled from the user's ``user_settings`` row at
generation time. ``display_name`` (also from settings) replaces every
"Linh"-branded reference. ``children`` (also from settings) drives the
school grade-filter rule.
"""

from __future__ import annotations

from datetime import date

from app import kids


def _render_sections_table(sections: list[dict]) -> str:
    """Render the user's section list as a numbered, ordered list. The
    LLM gets stable ``key``s so the server can detect missing sections
    and re-roll them."""
    lines = []
    for i, sec in enumerate(sections, 1):
        key = sec.get("key", "")
        title = (sec.get("title") or "").strip()
        desc = (sec.get("description") or "").strip()
        n = int(sec.get("subsection_count", 5))
        prefs = [p for p in (sec.get("preferred_sources") or []) if p]
        use_global = bool(sec.get("use_global_sources", True))
        lines.append(f"### {i}. `{key}` — {title}")
        lines.append(f"Minimum: {n} distinct fresh subsections (more is fine).")
        if desc:
            lines.append(f"Topic: {desc}")
        if prefs:
            lines.append(
                "Always check these preferred sources on every run, in addition "
                "to any other relevant sources you find: " + ", ".join(prefs) + "."
            )
            if not use_global:
                lines.append(
                    "Use ONLY these preferred sources for this section — do NOT "
                    "browse outside them."
                )
        lines.append("")
    return "\n".join(lines)


def _render_children_block(children_json: list[dict], today: date) -> str:
    parsed = kids.parse_children(children_json)
    if not parsed:
        return "(no children configured)"
    out = []
    for c in parsed:
        g = kids.grade_for(c["birthday"], today)
        a = kids.age_on(c["birthday"], today)
        out.append(f"- {c['name']}: age {a}, {kids.grade_label(g)}")
    return "\n".join(out)


def build_prompt(
    *,
    display_name: str,
    today: date,
    sections: list[dict],
    children: list[dict],
    watchlist_stocks: list[str],
    dorchester_events: str,
) -> str:
    """Return the full system prompt sent to Claude. All `{{...}}` style
    placeholders that used to live in news.pr are now substituted in
    Python; the LLM receives a complete, ready-to-read prompt."""

    name = display_name.strip() or "the reader"
    sections_table = _render_sections_table(sections)
    children_block = _render_children_block(children, today)
    grade_label = kids.grades_label(children, today) or "(none)"

    forbidden = (
        f"- **Do not** include any \"Generated for…\", \"Generated by…\", "
        f"\"Compiled for {name}\", \"Refresh Edition\", \"Noon Edition\", "
        "\"Midnight Edition\", or any reference to which slot triggered the "
        "run.\n"
        f"- **Do not** include any \"{name} News\" / \"The {name} News\" "
        "text — the page chrome supplies the masthead.\n"
        "- **Do not mention any of the children's names** anywhere in any "
        "text field, with the single exception of calendar events whose "
        "original title contains a child's name (render that title verbatim). "
        "No \"for William, age 8\" tags, no \"appropriate for a kid in 2nd "
        "grade\" headlines.\n"
        "- **Do not include any HTML tags** in `title` or `text` fields. "
        "The renderer escapes them.\n"
        "- **Do not invent** event dates for any school items — use the "
        "authoritative `DORCHESTER_CALENDAR_EVENTS` list verbatim."
    )

    today_iso = today.isoformat()
    watchlist_repr = ", ".join(watchlist_stocks) if watchlist_stocks else "(empty)"

    return f"""# Daily Generation Prompt

You are generating {name}'s personalised daily edition for {today_iso}.
All facts must be dated within 1–2 days of {today_iso}. Use the `web_search`
tool aggressively.

## Output contract

You return data — **never HTML**. Call the `return_edition` tool exactly
once with a JSON object matching this schema:

```
NewsEdition
  sections:  Section[]   # one per section listed below, in the same order
    key:           the stable key from the section list below
    title:         display title (use the title verbatim from the section list)
    subsections:   Subsection[]   # ≥ the target count for that section
      title:       plain-text headline
      text:        plain-text body, paragraphs separated by blank lines.
                   Bullet points are written as lines beginning with "- ".
                   NO HTML — no <p>, <ul>, <li>, <a>, <span>, etc.
      sources:     ≥1 source per item, each {{url, title}}, sorted most-relevant first.
                   `url` must point directly to the article so it stays readable
                   for several days. `title` is "Outlet: Headline".
  stocks: Stock[]    # one per ticker in the watchlist, in order. [] if empty.
    ticker:          symbol, e.g. "GOOG"
    price:           rendered verbatim, e.g. "$182.45"
    percent_diff:    signed daily % change as a number, e.g. -1.4 or 2.3
    why_it_moved:
      text:          plain-text explanation (no HTML, no bullets needed).
                     Depth scales with |percent_diff|:
                       <2%   → one sentence (e.g. "trading flat alongside the S&P")
                       2–5%  → 2–3 sentences with the catalyst
                       >5%   → fuller multi-source rundown
      sources:       ≥5 entries, sorted MOST-TRUSTED FIRST. Tier hierarchy:
                       1. Reuters / Bloomberg / WSJ / FT / AP / SEC filings / IR releases
                       2. CNBC / Barron's / MarketWatch / Economist / Forbes-staff
                       3. Yahoo Finance / Investopedia / Seeking-Alpha-staff / TechCrunch
                       4. Anything else (Reddit, blogs) — only if Tier 1–3 are exhausted
```

## Forbidden

{forbidden}

## Required sections

Each section listed below is REQUIRED in this edition. Hit at least the
minimum number of distinct fresh subsections per section — more is fine
when the news warrants it. If your initial search returns fewer than
the minimum, run additional `web_search` queries (broader terms, related
angles, regional outlets) until you have enough. If a genuine multi-query
search still produces fewer than the minimum, ship what you have plus a
one-line note explaining the slow news day in the last subsection's
text — never silently drop a section.

{sections_table}

Authoritative upcoming school events — use these dates verbatim:
```
{dorchester_events}
```

## Stocks section

For each symbol in the watchlist (in order), produce one Stock entry. If
the watchlist is empty, return `stocks: []`.

For every stock, run `web_search` to find **at least 5 distinct sources**
explaining today's price action (earnings reports, analyst notes,
regulatory news, sector moves, broad-market context — whatever applies).
Even on quiet days the broad-market read (S&P / Nasdaq, sector ETF) plus
any analyst coverage qualifies. Sort the sources most-trusted first per
the tier hierarchy in the schema above. Make sure each `url` points
directly to the article so it stays readable a few days later.

## Other context

- Today's date: {today_iso}
- Children (name, age, current grade — informational only; never name them):
{children_block}
- Current school grade(s) covered by the grade-filter rule: {grade_label}
- Watchlist tickers (in order): {watchlist_repr}

Weather, calendar, and movies are rendered server-side from local data —
**do not include them** in the output.
"""
