"""Add ``user_settings.user_id`` — a stable numeric handle starting at 1.

Used as the URL fallback for ``/pdf/{day}/{name}`` and ``/d/{day}/{name}``
when display names collide. Backfilled in the order users were added
(approximated by alphabetical email since there is no created_at column),
with the admin row pinned to id=1 so its handle never shifts.

Revision ID: 0027_user_id
Revises: 0026_user_pdf_token
Create Date: 2026-05-05
"""

from __future__ import annotations

import os

import sqlalchemy as sa
from alembic import op

revision = "0027_user_id"
down_revision = "0026_user_pdf_token"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "user_settings", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    bind = op.get_bind()
    admin = (os.environ.get("ADMIN_EMAIL") or "vtlinh87@gmail.com").lower()
    rows = (
        bind.execute(sa.text("SELECT email FROM user_settings ORDER BY email"))
        .scalars()
        .all()
    )
    ordered = ([admin] if admin in rows else []) + [e for e in rows if e != admin]
    next_id = 1
    for email in ordered:
        bind.execute(
            sa.text("UPDATE user_settings SET user_id = :i WHERE email = :e"),
            {"i": next_id, "e": email},
        )
        next_id += 1
    op.alter_column("user_settings", "user_id", nullable=False)
    op.create_unique_constraint(
        "uq_user_settings_user_id", "user_settings", ["user_id"]
    )
    # Convert to a Postgres identity column so future INSERTs auto-assign
    # the next id. Skipped on non-Postgres backends (e.g. SQLite tests).
    if bind.dialect.name == "postgresql":
        bind.execute(
            sa.text(
                f"ALTER TABLE user_settings ALTER COLUMN user_id "
                f"ADD GENERATED BY DEFAULT AS IDENTITY (START WITH {next_id})"
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        bind.execute(
            sa.text(
                "ALTER TABLE user_settings ALTER COLUMN user_id DROP IDENTITY IF EXISTS"
            )
        )
    op.drop_constraint("uq_user_settings_user_id", "user_settings", type_="unique")
    op.drop_column("user_settings", "user_id")
